### ISSUE TITLE
Can't generate keys when python is built with scrypt

### ISSUE THREAD

**Issue by viklund** [EGA-archive/crypt4gh#8]
## Problem

When trying to generate keys with `crypt4gh-keygen` I get the following error:

```
Traceback (most recent call last):
  File "/private/tmp/venv/bin/crypt4gh-keygen", line 8, in <module>
    sys.exit(main())
  File "/private/tmp/venv/lib/python3.8/site-packages/crypt4gh/keys.py", line 263, in main
    run(argv)
  File "/private/tmp/venv/lib/python3.8/site-packages/crypt4gh/keys.py", line 259, in run
    generate(seckey, pubkey, callback=cb, comment=comment)
  File "/private/tmp/venv/lib/python3.8/site-packages/crypt4gh/keys.py", line 149, in generate
    pkey = _encode_encrypted_private_key(sk, passphrase.encode(), comment)
  File "/private/tmp/venv/lib/python3.8/site-packages/crypt4gh/keys.py", line 114, in _encode_encrypted_private_key
    derived_key = _derive_key(kdfname, passphrase, salt, rounds)
  File "/private/tmp/venv/lib/python3.8/site-packages/crypt4gh/keys.py", line 89, in _derive_key
    return scrypt(passphrase, salt, 1<<14, 8, 1, dklen=32)
TypeError: scrypt() takes exactly 1 positional argument (5 given)
```

## Steps to reproduce

1. Make sure that python is built against OpenSSL 1.1. Can be done by trying to import the `scrypt` function from `hashlib` for example.
2. Run:
```crypt4gh-keygen --pk a --sk b```

## Suggested solution
Update the call to `scrypt` to take keyword arguments instead of positional.

**Comment by silverdaz** [comment]
Apparently this is the case for Python 3.7.
I have guarded the code: try to import scrypt, if it fails, don't use it.

But the issue is different, I encountered the same when I install python 3.8 from scratch: The arguments to scrypt are keyword-arguments. I have fixed it in commit #b876114
